const basepluscards = {"corp":{
"CrediCor":{"cardNum":"Z01","tags":[],"resources":{"mc":57},"prod":{},"type":"blue","cardExtra":"Effect:\n-20: 4\n(Effect: After you pay for a card or standard project with a basic cost of 20 mc or more, you gain 4 mc.)"},
"EcoLine":{"cardNum":"Z02","tags":["plant"],"resources":{"mc":36,"plant":3},"prod":{"plant":2},"type":"blue","cardExtra":"Effect:\n7 plant -> Greenery Tile\n(Effect: You may always pay 7 plants, instead of 8, to place 1 greenery.)"},
"Helion":{"cardNum":"Z03","tags":["space"], "resources":{"mc":42},"prod":{"heat":3},"type":"blue","cardExtra":"Effect:\nX heat = X mc\n(Effect: You may use heat as mc. You may not use mc as heat.)"},
"MiningGuild":{"cardNum":"Z04","tags":["building","building"],"resources":{"mc":30,"steel":5},"prod":{"steel":1},"type":"blue","cardExtra":"Effect:\nsteel/ti: (Effect: Each time you get any steel or ti as a placement bonus on the map, increase your steel production 1 step.)"},
"InterplanetaryCinematics":{"cardNum":"Z05","tags":["building"], "resources":{"mc":30,"steel":20},"prod":{},"type":"blue","cardExtra":"Effect:\nEvent: 2 mc\n(Effect: Each time you play an event, you gain 2 mc.)"},
"Inventrix":{"cardNum":"Z06","tags":["science"], "resources":{"mc":45,"card":3},"prod":{},"type":"blue","cardExtra":"Effect:\nRequirements: O2/Ocean/Temp: +/- 2\n(Effect: Your temperature, oxygen, and ocean requirements are +2 or -2 steps, your choice in each case.)"},
"PhoboLog":{"cardNum":"Z07","tags":["space"], "resources":{"mc":23,"ti":10},"prod":{},"type":"blue","cardExtra":"Effect:\nti: +1 mc\n(Effect: Your ti resources are each worth 1 mc extra.)\n--- Ed. note: It is not \"Phoblog.\""},
"TharsisRepublic":{"cardNum":"Z08","tags":["building"], "resources":{"mc":40,"city":1},"prod":{},"type":"blue","cardExtra":"Effect:\nany-City*: mc:1\nCity: 3 mc\n(Effect: Whenever any city tile is placed ON MARS, increase your mc production 1 step. When you place a city tile, gain 3 mc.)\n-- Ed. note: Some printings don't have the word \"corporation\" at the top of this card. This is a misprint."},
"Thorgate":{"cardNum":"Z09","tags":["power"], "resources":{"mc":48},"prod":{"energy":1},"type":"blue","discount":{"power":3},"cardExtra":"Effect:\n(Effect: When playing a power card OR THE STANDARD PROJECT POWER plant, you pay 6 it."},
"UnitedNationsMarsInitiative":{"cardNum":"Z10","tags":["earth"],"resources":{"mc":40},"prod":{},"type":"blue","cardExtra":"Action:\n3 mc -> TR*\n(Action: If your Terraform Rating was raised this generations, you may pay 3 mc to raise it 1 step more.)"},
"Teractor":{"cardNum":"Z11","tags":["earth"],"resources":{"mc":60},"prod":{},"type":"blue","discount":{"earth":3},"cardExtra":""},
"SaturnSystems":{"cardNum":"Z12","tags":["jovian"],"resources":{"mc":42},"prod":{"ti":1},"type":"blue","cardExtra":"Effect:\nany-Jovian: mc:1\n(Effect: Each time any Jovian tag is put into play, including this, increase your mc production 1 step.)"},
},
"proj":{
"ColonizerTrainingCamp":{"cardNum":"001","tags":["jovian","building"],"cost":"8","resources":{},"prod":{},"req":{"maxo2":5},"vp":2,"type":"green","cardExtra":""},
"AsteroidMiningConsortium":{"cardNum":"002","tags":["jovian"],"cost":"13","resources":{},"prod":{"ti":1},"req":{"ti":1},"vp":1,"reduce":{"ti":1},"type":"green","cardExtra":""},
"DeepWellHeating":{"cardNum":"003","tags":["power","building"],"cost":"13","resources":{"temp":1},"prod":{"energy":1},"type":"green","cardExtra":""},
"CloudSeeding":{"cardNum":"004","cost":"11","resources":{},"prod":{"mc":-1,"plant":2},"req":{"ocean":3},"reduce":{"heat":1},"type":"green","cardExtra":""},
"SearchForLife":{"cardNum":"005","tags":["science"], "cost":"3","resources":{},"prod":{},"req":{"maxo2":6},"type":"blue","cardExtra":"1 mc -> Microbe*: Science Resource\n(Action: Spend 1 mc to reveal and discard the top card of the draw deck. If that card has a Microbe tag, add a Science resource here.)\n(3 VPs if you have one or more Science resources here.)\nVP: Science Resource*: 3\n"},
"InventorsGuild":{"cardNum":"006","tags":["science"], "cost":"9","resources":{},"prod":{},"type":"blue","cardExtra":"-> Action: LOOK AT THE TOP CARD AND EITHER BUY IT OR DISCARD IT"},
"MartianRails":{"cardNum":"007","tags":["building"], "cost":"13","resources":{},"prod":{},"type":"blue","cardExtra":"energy -> mc/any-City*\n(Action: Spend 1 energy to gain 1 mc for each City tile ON MARS.)"},
"Capital":{"cardNum":"008","tags":["city","building"],"cost":"26","resources":{},"prod":{"mc":5,"energy":-2},"req":{"ocean":4},"type":"green","cardExtra":"Special Tile\n(Place this tile. 1 ADDITIONAL VP FOR EACH OCEAN TILE ADJACENT TO THIS CITY TILE.)\nVP: 1/Ocean*"},
"Asteroid":{"cardNum":"009","tags":["space"],"tags":["event"],"cost":"14","resources":{"temp":1, "ti":2},"prod":{},"type":"red","remove":{"plant":3},"cardExtra":""},
"Comet":{"cardNum":"010","tags":["space"],"tags":["event"],"cost":"21","resources":{"ocean":1,"temp":1},"prod":{},"type":"red","remove":{"plant":3},"cardExtra":""},
"BigAsteroid":{"cardNum":"011","tags":["space"],"tags":["event"],"cost":"27","resources":{"temp":2, "ti":4},"prod":{},"type":"red","remove":{"plant":4},"cardExtra":""},
"WaterImportFromEuropa":{"cardNum":"012","tags":["jovian","space"],"cost":"25","resources":{},"prod":{},"type":"blue","cardExtra":"12 mc (ti) -> Ocean Tile\n(Action: Pay 12 mc to place an ocean tile. ti MAY BE USED as if playing a Space card.)\n------\n(1 VP for each Jovian tag you have.)\nVP: 1/Jovian"},
"SpaceElevator":{"cardNum":"013","tags":["space","building"],"cost":"27","resources":{},"prod":{"ti":1},"vp":2,"type":"blue","cardExtra":"steel -> 5 mc\n(Action: Spend 1 steel to gain 5 mc.)\n"},
"DevelopmentCenter":{"cardNum":"014","tags":["science","building"],"cost":"11","resources":{},"prod":{},"type":"blue","cardExtra":"energy -> +Card\n(Action: Spend 1 energy to draw a card.)"},
"EquatorialMagnetizer":{"cardNum":"015","tags":["building"], "cost":"11","resources":{},"prod":{},"type":"blue","cardExtra":"Decrease energy 1 -> TR\n(Action: Decrease your energy production 1 step to increase your terraform rating 1 step.)"},
"DomedCrater":{"cardNum":"016","tags":["city","building"],"cost":"24","resources":{"city":1,"plant":3},"prod":{"energy":-1,"mc":3,},"req":{"maxo2":7},"vp":1,"type":"green","cardExtra":""},
"NoctisCity":{"cardNum":"017","tags":["city","building"],"cost":"18","resources":{},"prod":{"energy":-1,"mc":3,},"type":"green","cardExtra":"City Tile*\n(Place a City ON THE RESERVED AREA, disregarding normal placement restrictions.)"},
"MethaneFromTitan":{"cardNum":"018","tags":["jovian","space"],"cost":"28","resources":{},"prod":{"heat":2,"plant":2},"req":{"o2":2},"vp":2,"type":"green","cardExtra":""},
"ImportedHydrogen":{"cardNum":"019","tags":["earth","space","event"],"cost":"16","resources":{"ocean":1},"prod":{},"type":"red","cardExtra":"3 plants OR 3 Microbe* Resource OR 2 Animal* resource\n(Gain 3 plants, or add 3 Microbes or 2 Animals to ANOTHER card.)"},
"ResearchOutpost":{"cardNum":"020","tags":["science", "city","building"],"cost":"18","resources":{},"prod":{},"type":"blue","discount":{"any":1},"cardExtra":"City Tile*\n(Place a city tile NEXT TO NO OTHER TILE.)"},
"PhobosSpaceHaven":{"cardNum":"021","tags":["space","city"],"cost":"25","resources":{},"prod":{"ti":1},"vp":3,"type":"green","cardExtra":"City Tile*\n(Increase your ti production 1 step and place a City tile ON THE RESERVED AREA.)\n"},
"BlackPolarDust":{"cardNum":"022","cost":"15","resources":{"ocean":1},"prod":{"heat":3,"mc":-2},"type":"green","cardExtra":""},
"ArcticAlgae":{"cardNum":"023","tags":["plant"],"cost":"12","resources":{"plant":1},"prod":{},"req":{"maxtemp":-12},"type":"blue","cardExtra":"any-Ocean Tile: plant plant\n(Effect: When anyone places an ocean tile, gain 2 plants.)\n------\n\n(It must be -12 C or colder to play. Gain 1 plant.)"},
"Predators":{"cardNum":"024","tags":["animal"],"cost":"14","resources":{},"prod":{},"req":{"o2":11},"type":"blue","cardExtra":"any-Animal Resource -> Animal Resource\n(Action: Remove 1 Animal from any card and add it to this card.)\n------\n(Requires 11% oxygen. 1 VP per Animal on this card.)\nVP: 1/Animal"},
"SpaceStation":{"cardNum":"025","tags":["space"], "cost":"10","resources":{},"prod":{},"vp":1,"type":"blue","discount":{"space":2},"cardExtra":""},
"EOSChasmaNationalPark":{"cardNum":"026","tags":["plant","building"],"cost":"16","resources":{"plant":3},"prod":{"mc":2,},"req":{"temp":-12},"vp":1,"type":"green","cardExtra":"Animal* Resource\n(Add 1 Animal TO ANY ANIMAL CARD.)\n"},
"InterstellarColonyShip":{"cardNum":"027","tags":["earth","space","event"],"cost":"24","resources":{},"prod":{},"req":{"science":5},"vp":4,"type":"red","cardExtra":""},
"SecurityFleet":{"cardNum":"028","tags":["space"], "cost":"12","resources":{},"prod":{},"type":"blue","cardExtra":"ti -> Fighter Resource\n(Action: Spend 1 ti to add 1 fighter resource to this card.)\n------\n(1 VP for each fighter resource on this card.)\nVP: 1/Fighter Resource"},
"CupolaCity":{"cardNum":"029","tags":["city","building"],"cost":"16","resources":{"city":1},"prod":{"energy":-1,"mc":3,},"req":{"maxo2":9},"type":"green","cardExtra":""},
"LunarBeam":{"cardNum":"030","tags":["earth","power"],"cost":"13","resources":{},"prod":{"heat":2,"energy":2,"mc":-2},"type":"green","cardExtra":""},
"OptimalAerobraking":{"cardNum":"031","tags":["space"], "cost":"7","resources":{},"prod":{},"type":"blue","cardExtra":"Space Event: 3 mc heat heat heat\n(Effect: When you play a Space Event, you gain 3 mc and 3 heat.)"},
"UndergroundCity":{"cardNum":"032","tags":["city","building"],"cost":"18","resources":{"city":1},"prod":{"energy":-2,"steel":2},"type":"green","cardExtra":""},
"RegolithEaters":{"cardNum":"033","tags":["science","microbe"],"cost":"13","resources":{},"prod":{},"type":"blue","cardExtra":"-> Microbe\nOR Microbe Microbe -> O2\n(Action: Add 1 Microbe to this card, or remove 2 Microbes from this card to raise oxygen level 1 step.)"},
"GHGProducingBacteria":{"cardNum":"034","tags":["science","microbe"],"cost":"8","resources":{},"prod":{},"req":{"o2":4},"type":"blue","cardExtra":"-> Microbe Resource\nOR Microbe Resource Microbe Resource -> TempUp 1\n(Action: Add 1 Microbe to this card, or remove 2 Microbes to raise temperature 1 step.)\n------\n(Requires 4% oxygen.)"},
"Ants":{"cardNum":"035","tags":["microbe"],"cost":"9","resources":{},"prod":{},"req":{"o2":4},"type":"blue","cardExtra":"any-Microbe Resource -> Microbe Resource\n(Action: Remove 1 Microbe from any card to add 1 to this card.)\n------\n(Requires 4% oxygen. 1 VP per 2 Microbes on this card.)\nVP: 1/2 Microbe Resource"},
"ReleaseOfInertGases":{"cardNum":"036","tags":["event"],"cost":"14","resources":{"tr":2},"prod":{},"type":"red","cardExtra":""},
"NitrogenRichAsteroid":{"cardNum":"037","tags":["space"],"tags":["event"],"cost":"31","resources":{"tr":2,"temp":1},"prod":{"plant":1},"type":"red","cardExtra":"Increase plant 1 OR\nIf 3 plant tags:(Raise your terraforming rating 2 steps and temperature 1 step. Increase your plant production 1 step, or 4 steps if you have 3 plant tags.)"},
"RoverConstruction":{"cardNum":"038","tags":["building"], "cost":"8","resources":{},"prod":{},"vp":1,"type":"blue","cardExtra":"any-City: 2\n(Effect: When any City tile is placed, gain 2 mc.)\n------\n"},
"DeimosDown":{"cardNum":"039","tags":["space"],"tags":["event"],"cost":"31","resources":{"temp":3,"steel":4},"prod":{},"type":"red","remove":{"plant":8},"cardExtra":""},
"AsteroidMining":{"cardNum":"040","tags":["jovian","space"],"cost":"30","resources":{},"prod":{"ti":2},"vp":2,"type":"green","cardExtra":""},
"FoodFactory":{"cardNum":"041","tags":["building"], "cost":"12","resources":{},"prod":{"mc":4,"plant":-1},"vp":1,"type":"green","cardExtra":""},
"ArchaeBacteria":{"cardNum":"042","tags":["microbe"],"cost":"6","resources":{},"prod":{"plant":1},"req":{"maxtemp":-18},"type":"green","cardExtra":""},
"CarbonateProcessing":{"cardNum":"043","tags":["building"], "cost":"6","resources":{},"prod":{"energy":-1,"heat":3},"type":"green","cardExtra":""},
"NaturalPreserve":{"cardNum":"044","tags":["science","building"],"cost":"9","resources":{},"prod":{"mc":1,},"req":{"maxo2":4},"vp":1,"type":"green","cardExtra":"Special Tile*\n(Place this tile NEXT TO NO OTHER TILE.)\n"},
"NuclearPower":{"cardNum":"045","tags":["power","building"],"cost":"10","resources":{},"prod":{"energy":3,"mc":-2},"type":"green","cardExtra":""},
"LightningHarvest":{"cardNum":"046","tags":["power"], "cost":"8","resources":{},"prod":{"energy":1,"mc":1},"req":{"science":3},"vp":1,"type":"green","cardExtra":""},
"Algae":{"cardNum":"047","tags":["plant"],"cost":"10","resources":{"plant":1},"prod":{"plant":2},"req":{"ocean":5},"type":"green","cardExtra":""},
"AdaptedLichen":{"cardNum":"048","tags":["plant"],"cost":"9","resources":{},"prod":{"plant":1},"type":"green","cardExtra":""},
"Tardigrades":{"cardNum":"049","tags":["microbe"],"cost":"4","resources":{},"prod":{},"type":"blue","cardExtra":"-> Microbe Resource\n(Action: Add 1 Microbe to this card.)\n------\n(1 VP per 4 Microbes on this card.)\nVP: 1/4 Microbe Resource)"},
"Virus":{"cardNum":"050","tags":["microbe","event"],"cost":"1","resources":{},"prod":{},"type":"red","cardExtra":"Remove 2 any-Animal OR -5 any-plant\n(Remove up to 2 Animals or 5 plants from any player.)"},
"MirandaResort":{"cardNum":"051","tags":["jovian","space"],"cost":"12","resources":{},"prod":{},"vp":1,"type":"green","cardExtra":"Increase mc/Earth\n(Increase your mc production 1 step for each Earth tag you have.)\n"},
"Fish":{"cardNum":"052","tags":["animal"],"cost":"9","resources":{},"prod":{},"req":{"temp":2},"type":"blue","cardExtra":"-> Animal Resource\n(Action: Add 1 Animal to this card.)\n------\nReduce any-plant 1\n(Requires +2 C or warmer. Decrease any plant production 1 step. 1 VP for each Animal on this card.)\nVP: 1/Animal Resource"},
"LakeMarineris":{"cardNum":"053","cost":"18","resources":{"ocean":2},"prod":{},"req":{"temp":0},"vp":2,"type":"green","cardExtra":""},
"SmallAnimals":{"cardNum":"054","tags":["animal"],"cost":"6","resources":{},"prod":{},"req":{"o2":6},"reduce":{"plant":1},"type":"blue","cardExtra":"-> Animal Resource\n(Action: Add 1 Animal to this card.)\n------\n\n(Requires 6% oxygen. Decrease any plant production 1 step. 1 VP per 2 Animals on this card.)\nVP: 1/2 Animal Resource"},
"KelpFarming":{"cardNum":"055","tags":["plant"],"cost":"17","resources":{"plant":2},"prod":{"mc":2,"plant":3},"req":{"ocean":6},"vp":1,"type":"green","cardExtra":""},
"Mine":{"cardNum":"056","tags":["building"], "cost":"4","resources":{},"prod":{"steel":1},"type":"green","cardExtra":""},
"VestaShipyard":{"cardNum":"057","tags":["jovian","space"],"cost":"15","resources":{},"prod":{"ti":1},"vp":1,"type":"green","cardExtra":""},
"BeamFromAThoriumAsteroid":{"cardNum":"058","tags":["jovian"],"tags":["space","power"],"cost":"32","resources":{},"prod":{"heat":3,"energy":3},"req":{"jovian":1},"vp":1,"type":"green","cardExtra":""},
"Mangrove":{"cardNum":"059","tags":["plant"],"cost":"12","resources":{},"prod":{},"req":{"temp":4},"vp":1,"type":"green","cardExtra":"Greenery Tile*\n(Place a greenery tile ON AN AREA RESERVED FOR OCEAN and raise oxygen 1 step. Disregard normal placement restrictions for this.)\n"},
"Trees":{"cardNum":"060","tags":["plant"],"cost":"13","resources":{"plant":1},"prod":{"plant":3},"req":{"temp":-4},"vp":1,"type":"green","cardExtra":""},
"GreatEscarpmentConsortium":{"cardNum":"061","cost":"6","resources":{},"prod":{"steel":1},"req":{},"reduce":{"steel":1},"type":"green","cardExtra":"(Decrease any steel production 1 step and increase your own 1 step.)"},
"MineralDeposit":{"cardNum":"062","tags":["event"],"cost":"5","resources":{"steel":5},"prod":{},"type":"red","cardExtra":""},
"MiningExpedition":{"cardNum":"063","tags":["event"],"cost":"12","resources":{"o2":1,"steel":2},"prod":{},"type":"red","cardExtra":"(Remove 2 plants from any player.)"},
"MiningArea":{"cardNum":"064","tags":["building"], "cost":"4","resources":{},"prod":{},"type":"green","cardExtra":"Special Tile*\n[Increase steel 1 OR ti 1]*\n(Place this tile on an area with a steel or ti placement bonus, adjacent to another of your tiles. Increase your production of that resource 1 step.)"},
"BuildingIndustries":{"cardNum":"065","tags":["building"], "cost":"6","resources":{},"prod":{"energy":-1,"steel":2},"type":"green","cardExtra":""},
"LandClaim":{"cardNum":"066","tags":["event"],"cost":"1","resources":{},"prod":{},"type":"red","cardExtra":"PLACE YOUR MARKER ON A NON-RESERVED AREA. ONLY YOU MAY PLACE A TILE HERE."},
"MiningRights":{"cardNum":"067","tags":["building"], "cost":"9","resources":{},"prod":{},"type":"green","cardExtra":"Special Tile*\nIncrease steel 1 or ti 1\n(Place this tile on an area with a steel or ti placement bonus. Increase that production 1 step.)"},
"Sponsors":{"cardNum":"068","tags":["earth"],"cost":"6","resources":{},"prod":{"mc":2},"type":"green","cardExtra":""},
"ElectroCatapult":{"cardNum":"069","tags":["building"], "cost":"17","resources":{},"prod":{"energy":-1},"req":{"maxo2":8},"vp":1,"type":"blue","cardExtra":"plant/steel -> 7 mc\n(Action: Spend 1 plant or 1 steel to gain 7 mc.)"},
"EarthCatapult":{"cardNum":"070","tags":["earth"],"cost":"23","resources":{},"prod":{},"vp":2,"type":"blue","discount":{"any":2},"cardExtra":""},
"AdvancedAlloys":{"cardNum":"071","tags":["science"], "cost":"9","resources":{},"prod":{},"type":"blue","cardExtra":"ti: +1 mc\nsteel: +1mc\n(Effect: Each ti you have is worth 1 mc extra. Each steel you have is worth 1 mc extra.)"},
"Birds":{"cardNum":"072","tags":["animal"],"cost":"10","resources":{},"prod":{},"req":{"o2":13},"reduce":{"plant":2},"type":"blue","cardExtra":"-> Animal Resource\n(Action: Add an Animal to this card.)\n------\n\n(Requires 13% oxygen. Decrease any plant production 2 steps. 1 VP for each Animal on this card.)\nVP: 1/Animal"},
"MarsUniversity":{"cardNum":"073","tags":["science","building"],"cost":"8","resources":{},"prod":{},"vp":1,"type":"blue","cardExtra":"Science: -Card +Card\nEffect: When you play a Science tag, including this, you may discard a card from hand to draw a card.\n------\n"},
"ViralEnhancers":{"cardNum":"074","tags":["science","microbe"],"cost":"9","resources":{},"prod":{},"type":"blue","cardExtra":"plant/Microbe/Animallant/Microbe*/Animal*\n(Effect: When you play a plant, Microbe, or an Animal tag, including this, gain 1 plant or add 1 resource TO THAT CARD.)"},
"TowingAComet":{"cardNum":"075","tags":["space"],"tags":["event"],"cost":"23","resources":{"ocean":1,"o2":1,"plant":2},"prod":{},"type":"red","cardExtra":""},
"SpaceMirrors":{"cardNum":"076","tags":["power","space"],"cost":"3","resources":{},"prod":{"energy":1},"type":"blue","cardExtra":"7 mc -> (Action: Spend 7 mc to increase your energy production 1 step.)"},
"SolarWindPower":{"cardNum":"077","tags":["science"],"tags":["space","power"],"cost":"11","resources":{"ti":2},"prod":{"energy":1},"type":"green","cardExtra":""},
"IceAsteroid":{"cardNum":"078","tags":["space"],"tags":["event"],"cost":"23","resources":{"ocean":2},"prod":{},"type":"red","cardExtra":""},
"QuantumExtractor":{"cardNum":"079","tags":["science","power"],"cost":"13","resources":{},"prod":{"energy":4},"req":{"science":4},"type":"blue","discount":{"space":2},"cardExtra":""},
"GiantIceAsteroid":{"cardNum":"080","tags":["space"],"tags":["event"],"cost":"36","resources":{"ocean":2,"temp":2},"prod":{},"type":"red","remove":{"plant":6},"cardExtra":""},
"GanymedeColony":{"cardNum":"081","tags":["jovian"],"tags":["space","city"],"cost":"20","resources":{},"prod":{},"type":"green","cardExtra":"City Tile*\n(Place a City tile ON THE RESERVED AREA. 1 VP per Jovian tag you have.)\nVP: 1/Jovian"},
"CallistoPenalMines":{"cardNum":"082","tags":["jovian","space"],"cost":"24","resources":{},"prod":{"mc":3,},"vp":2,"type":"green","cardExtra":""},
"GiantSpaceMirror":{"cardNum":"083","tags":["power","space"],"cost":"17","resources":{},"prod":{"energy":3},"type":"green","cardExtra":""},
"TransNeptuneProbe":{"cardNum":"084","tags":["science","space"],"cost":"6","resources":{},"prod":{},"vp":1,"type":"green","cardExtra":""},
"CommercialDistrict":{"cardNum":"085","tags":["building"], "cost":"16","resources":{},"prod":{"energy":-1,"mc":4,"energy":1},"type":"green","cardExtra":"Special Tile\n( Place this tile. 1 VP PER ADJACENT CITY TILE.)\nVP: 1/City*"},
"RoboticWorkforce":{"cardNum":"086","tags":["science"], "cost":"9","resources":{},"prod":{},"type":"green","cardExtra":"COPY A Building.\n(Duplicate only the production box of one of your Building cards.)"},
"Grass":{"cardNum":"087","tags":["plant"],"cost":"11","resources":{"plant":3},"prod":{"plant":1},"req":{"temp":-16},"type":"green","cardExtra":""},
"Heather":{"cardNum":"088","tags":["plant"],"cost":"6","resources":{"plant":1},"prod":{"plant":1},"req":{"temp":-14},"type":"green","cardExtra":""},
"PeroxidePower":{"cardNum":"089","tags":["power","building"],"cost":"7","resources":{},"prod":{"mc":-1,"energy":2},"type":"green","cardExtra":""},
"Research":{"cardNum":"090","tags":["science","science"],"cost":"11","resources":{"card":2},"prod":{},"vp":1,"type":"green","cardExtra":""},
"GeneRepair":{"cardNum":"091","tags":["science"], "cost":"12","resources":{},"prod":{"mc":2,},"req":{"science":3},"vp":2,"type":"green","cardExtra":""},
"IoMiningIndustries":{"cardNum":"092","tags":["jovian","space"],"cost":"41","resources":{},"prod":{"mc":2,"ti":2},"type":"green","cardExtra":"1 VP per Jovian tag you have.)\n1/Jovian"},
"Bushes":{"cardNum":"093","tags":["plant"],"cost":"10","resources":{"plant":2},"prod":{"plant":2},"req":{"temp":-10},"type":"green","cardExtra":""},
"MassConverter":{"cardNum":"094","tags":["science","power"],"cost":"8","resources":{},"prod":{"energy":6},"req":{"science":5},"type":"blue","discount":{"space":2},"cardExtra":""},
"PhysicsComplex":{"cardNum":"095","tags":["science","building"],"cost":"12","resources":{},"prod":{},"type":"blue","cardExtra":"6 energy -> Science Resource\n(Action: Spend 6 energy to add a Science resource to this card.)\n------\n(2 VP for each Science resource on this card.)\nVP: 2/Science Resource"},
"Greenhouses":{"cardNum":"096","tags":["plant","building"],"cost":"6","resources":{},"prod":{},"type":"green","cardExtra":"plant/any-City\n(Gain 1 plant for each City tile in play.)"},
"NuclearZone":{"cardNum":"097","tags":["earth"],"cost":"10","resources":{"temp":2},"prod":{},"vp":-2,"type":"green","cardExtra":"Special Tile\n(Place this tile.)\n"},
"TropicalResort":{"cardNum":"098","tags":["building"], "cost":"13","resources":{},"prod":{"mc":3,"heat":-2},"vp":2,"type":"green","cardExtra":""},
"TollStation":{"cardNum":"099","tags":["space"], "cost":"12","resources":{},"prod":{},"type":"green","cardExtra":"Increase 1 mc/Space*\n(Increase your mc production 1 step for each Space tag OPPONENTS have.)"},
"FueledGenerators":{"cardNum":"100","tags":["power","building"],"cost":"1","resources":{},"prod":{"mc":-1,"energy":1},"type":"green","cardExtra":""},
"Ironworks":{"cardNum":"101","tags":["building"], "cost":"11","resources":{},"prod":{},"type":"green","cardExtra":"4 energy -> steel O2\n(Action Spend 4 energy to gain 1 steel and increase oxygen 1 step.)"},
"PowerGrid":{"cardNum":"102","tags":["power"], "cost":"18","resources":{},"prod":{},"type":"green","cardExtra":"Increase energy/energy tag\n(Increase your energy production step for each energy tag you have, including this.)"},
"Steelworks":{"cardNum":"103","tags":["building"], "cost":"15","resources":{},"prod":{},"type":"blue","cardExtra":"4 energy -> steel steel O2\n(Action: Spend 4 energy to gain 2 steel and increase oxygen 1 step.)"},
"OreProcessor":{"cardNum":"104","tags":["building"], "cost":"13","resources":{},"prod":{},"type":"blue","cardExtra":"4 energy -> ti O2\n(Action: Spend 4 energy to gain 1 ti and increase oxygen 1 step.)"},
"EarthOffice":{"cardNum":"105","tags":["earth"],"cost":"1","resources":{},"prod":{},"type":"blue","discount":{"earth":3},"cardExtra":""},
"AcquiredCompany":{"cardNum":"106","tags":["earth"],"cost":"10","resources":{},"prod":{"mc":3,},"type":"green","cardExtra":""},
"MediaArchives":{"cardNum":"107","tags":["earth"],"cost":"8","resources":{},"prod":{},"type":"green","cardExtra":"1 mc/Event*\n(Gain 1 mc for each Event EVER PLAYED by all players.)"},
"OpenCity":{"cardNum":"108","tags":["city","building"],"cost":"23","resources":{"city":1,"plant":2},"prod":{"energy":-1,"mc":4,"energy":1},"req":{"o2":12},"vp":1,"type":"green","cardExtra":""},
"MediaGroup":{"cardNum":"109","tags":["earth"],"cost":"6","resources":{},"prod":{},"type":"blue","cardExtra":"Event: 3 mc\n(Effect: After you play an Event card, you gain 3 mc.)"},
"BusinessNetwork":{"cardNum":"110","tags":["earth"],"cost":"4","resources":{},"prod":{"mc":1},"type":"blue","cardExtra":"-> Action: LOOK AT THE TOP CARD AND EITHER BUY IT OR DISCARD IT\n------\n(Decrease your mc production 1 step.)"},
"BusinessContacts":{"cardNum":"111","tags":["earth"],"tags":["event"],"cost":"7","resources":{},"prod":{},"type":"red","cardExtra":"LOOK AT THE TOP 4 CARDS FROM THE DECK. TAKE 2 OF THEM INTO HAND AND DISCARD THE OTHER 2"},
"BribedCommittee":{"cardNum":"112","tags":["earth"],"tags":["event"],"cost":"7","resources":{"tr":2},"prod":{},"vp":-2,"type":"red","cardExtra":""},
"SolarPower":{"cardNum":"113","tags":["power","building"],"cost":"11","resources":{},"prod":{"energy":1},"vp":1,"type":"green","cardExtra":""},
"BreathingFilters":{"cardNum":"114","tags":["science"], "cost":"11","resources":{},"prod":{},"req":{"o2":7},"vp":2,"type":"green","cardExtra":""},
"ArtificialPhotosynthesis":{"cardNum":"115","tags":["science"], "cost":"12","resources":{},"prod":{},"type":"green","cardExtra":"Increase plant 1 OR energy 2\n(Increase your plant production 1 step or your energy production 2 steps.)"},
"ArtificialLake":{"cardNum":"116","tags":["building"], "cost":"15","resources":{"ocean":1},"prod":{},"req":{"temp":-6},"vp":1,"type":"green","cardExtra":"Ocean Tile*\n(Requires -6 C or warmer. Place 1 ocean tile ON AN AREA NOT RESERVED FOR OCEAN.)\n"},
"GeothermalPower":{"cardNum":"117","tags":["power","building"],"cost":"11","resources":{},"prod":{"energy":2},"type":"green","cardExtra":""},
"Farming":{"cardNum":"118","tags":["plant"],"cost":"16","resources":{"plant":2},"prod":{"mc":2,"plant":2},"req":{"temp":4},"vp":2,"type":"green","cardExtra":""},
"DustSeals":{"cardNum":"119","cost":"2","resources":{},"prod":{},"req":{"maxocean":3},"vp":1,"type":"green","cardExtra":""},
"UrbanizedArea":{"cardNum":"120","tags":["city","building"],"cost":"10","resources":{},"prod":{"energy":-1,"mc":2,"energy":1},"type":"green","cardExtra":"City Tile*\n( Place a City tile ADJACENT TO AT LEAST 2 OTHER CITY TILES.)"},
"Sabotage":{"cardNum":"121","tags":["event"],"cost":"1","resources":{},"prod":{},"type":"red","cardExtra":"-3 any-ti OR -4 any-steel OR -7 any-mc\n(Remove up to 3 ti from any player, or 4 steel, or 7 mc.)"},
"Moss":{"cardNum":"122","tags":["plant"],"cost":"4","resources":{"plant":-1},"prod":{"plant":1},"req":{"ocean":3},"type":"green","cardExtra":""},
"IndustrialCenter":{"cardNum":"123","tags":["building"], "cost":"4","resources":{},"prod":{},"type":"blue","cardExtra":"7 mc -> steel production\n(Action: Spend 7 mc to increase your steel production 1 step.)\n------\nSpecial Tile*\n(Place this tile ADJACENT TO A CITY TILE.)"},
"HiredRaiders":{"cardNum":"124","tags":["event"],"cost":"1","resources":{},"prod":{},"type":"red","cardExtra":"STEAL 2 any-steel\nOR STEAL 3 any-mc\n(Steal up to 2 steal, or 3 mc from any player.)"},
"Hackers":{"cardNum":"125","cost":"3","resources":{},"prod":{"energy":-1,"mc":2,"energy":1},"vp":-1,"reduce":{"mc":2},"type":"green","cardExtra":""},
"GHGFactories":{"cardNum":"126","tags":["building"], "cost":"11","resources":{},"prod":{"energy":-1,"heat":4},"type":"green","cardExtra":""},
"SubterraneanReservoir":{"cardNum":"127","tags":["event"],"cost":"11","resources":{"ocean":1},"prod":{},"type":"red","cardExtra":""},
"EcologicalZone":{"cardNum":"128","tags":["animal","plant"],"cost":"12","resources":{},"prod":{},"req":{"greenery":1},"type":"blue","cardExtra":"Animal/plant: Animal Resource\n(Effect: When you play an Animal or plant tag (including these 2), add an Animal to this card.)\n------\nSpecial Tile*\n(Requires that you have a greenery tile. Place this tile adjacent to any greenery tile. 1 VP per 2 Animals on this card.)\nVP: 1/2 Animal Resource"},
"Zeppelins":{"cardNum":"129","cost":"13","resources":{},"prod":{},"req":{"o2":5},"vp":1,"type":"green","cardExtra":"Increase mc/any-City*\n(Increase your mc production 1 step for each City tile ON MARS.)\n"},
"Worms":{"cardNum":"130","tags":["microbe"],"cost":"8","resources":{},"prod":{},"req":{"o2":4},"type":"green","cardExtra":"Increase plant/2 Microbe tags\n(Increase your plant production 1 step for every 2 Microbe tags you have, including this.)"},
"Decomposers":{"cardNum":"131","tags":["microbe"],"cost":"5","resources":{},"prod":{},"req":{"o2":3},"type":"blue","cardExtra":"Animal/plant/Microbe: Microbe Resource\n(Effect: When you play an Animal, plant, or Microbe tag, including this, add a Microbe to this card.)\n------\n( 1 VP per 3 Microbes on this card.)\nVP: 1/3 Microbe Resource"},
"FusionPower":{"cardNum":"132","tags":["science"],"tags":["power","building"],"cost":"14","resources":{},"prod":{"energy":3},"req":{"energy":2},"type":"green","cardExtra":""},
"SymbioticFungus":{"cardNum":"133","tags":["microbe"],"cost":"4","resources":{},"prod":{},"req":{"temp":-14},"type":"blue","cardExtra":"-> Microbe* Resource\n(Action: Add a Microbe to ANOTHER card.)\n"},
"ExtremeColdFungus":{"cardNum":"134","tags":["microbe"],"cost":"13","resources":{},"prod":{},"req":{"maxtemp":-10},"type":"blue","cardExtra":"-> plant\nOR -> Microbe Microbe*\n(Action: Gain 1 plant or add 2 Microbes to ANOTHER card.)\n------\n(It must be -10 C or colder.)"},
"AdvancedEcosystems":{"cardNum":"135","tags":["plant","microbe","animal"],"cost":"11","resources":{},"prod":{},"req":{"plant":1,"animal":1,"microbe":1},"vp":3,"type":"green","cardExtra":""},
"GreatDam":{"cardNum":"136","tags":["power","building"],"cost":"12","resources":{},"prod":{"energy":2},"req":{"ocean":4},"vp":1,"type":"green","cardExtra":""},
"Cartel":{"cardNum":"137","tags":["earth"],"cost":"8","resources":{},"prod":{"mc":1},"type":"green","cardExtra":"(Increase your mc production 1 step for each Earth tag you have, including this.)"},
"StripMine":{"cardNum":"138","tags":["building"], "cost":"25","resources":{"o2":2},"prod":{"energy":-2,"steel":2,"ti":1},"type":"green","cardExtra":""},
"WavePower":{"cardNum":"139","tags":["power"], "cost":"8","resources":{},"prod":{"energy":1},"req":{"ocean":3},"vp":1,"type":"green","cardExtra":""},
"LavaFlows":{"cardNum":"140","tags":["event"],"cost":"18","resources":{"temp":2},"prod":{},"type":"red","cardExtra":"Special Tile*\n(place this tile ON EITHER THARSIS THOLUS, ASCRAEUS MONS, PAVONIS MONS OR ARSIA MONS.)"},
"PowerPlant":{"cardNum":"141","tags":["power","building"],"cost":"4","resources":{},"prod":{"energy":1},"type":"green","cardExtra":""},
"MoholeArea":{"cardNum":"142","tags":["building"], "cost":"20","resources":{},"prod":{"heat":4},"type":"green","cardExtra":"Special Tile*\n(Increase your heat production 4 steps. Place this tile ON AN AREA RESERVED FOR OCEAN.)"},
"LargeConvoy":{"cardNum":"143","tags":["earth","space","event"],"cost":"36","resources":{"ocean":1,"card":2},"prod":{},"vp":2,"type":"red","cardExtra":"5 plant/4 Animal* Resource\n(Gain 5 plants or add 4 Animals to ANOTHER card.)\n"},
"TitaniumMine":{"cardNum":"144","tags":["building"], "cost":"7","resources":{},"prod":{"ti":1},"type":"green","cardExtra":""},
"TectonicStressPower":{"cardNum":"145","tags":["power","building"],"cost":"18","resources":{},"prod":{"energy":3},"req":{"science":2},"vp":1,"type":"green","cardExtra":""},
"NitrophilicMoss":{"cardNum":"146","tags":["plant"],"cost":"8","resources":{"plant":-2},"prod":{"plant":2},"req":{"ocean":3},"type":"green","cardExtra":""},
"Herbivores":{"cardNum":"147","tags":["animal"],"cost":"12","resources":{},"prod":{},"req":{"o2":8},"reduce":{"plant":1},"type":"blue","cardExtra":"plantation: Animal Resource\n(Effect: When you place a greenery tile, add an Animal to this card.)\n------\nAnimal Resource\n\n( Add 1 Animal to this card. Decrease any plant production 1 step. 1 VP per 2 Animals on this card.)\nVP: 1/2 Animal Resource"},
"Insects":{"cardNum":"148","tags":["microbe"],"cost":"9","resources":{},"prod":{},"req":{"o2":6},"type":"green","cardExtra":"\nIncrease plant/plant tag\n(Increase your plant production 1 step for each plant tag you have.)"},
"CEOsFavoriteProject":{"cardNum":"149","tags":["event"],"cost":"1","resources":{},"prod":{},"type":"red","cardExtra":"ADD 1 RESOURCE TO A CARD WITH AT LEAST 1 RESOURCE ON IT"},
"AntiGravityTechnology":{"cardNum":"150","tags":["science"], "cost":"14","resources":{},"prod":{},"req":{"science":7},"vp":3,"type":"blue","discount":{"any":2},"cardExtra":""},
"InvestmentLoan":{"cardNum":"151","tags":["earth"],"tags":["event"],"cost":"3","resources":{"mc":10},"prod":{"mc":-1},"type":"red","cardExtra":""},
"Insulation":{"cardNum":"152","cost":"2","resources":{},"prod":{},"type":"green","cardExtra":"Decrease heat X\nmc:X\n(Decrease your heat production any number of steps and increase your mc production the same number of steps.)"},
"AdaptationTechnology":{"cardNum":"153","tags":["science"], "cost":"12","resources":{},"prod":{},"vp":1,"type":"blue","cardExtra":"Requirements: O2/Ocean/Temp: +/- 2\n(Effect: Your global requirements are +2 or -2 steps, your choice in each case.)\n"},
"CaretakerContract":{"cardNum":"154","cost":"3","resources":{},"prod":{},"req":{"temp":0},"type":"blue","cardExtra":"8 heat -> TR\n(Action: Spend 8 heat to increase your terraform rating 1 step.)\n------\n(Requires 0 C or warmer.)"},
"DesignedMicroOrganisms":{"cardNum":"155","tags":["science","microbe"],"cost":"16","resources":{},"prod":{"plant":2},"req":{"maxtemp":-14},"type":"green","cardExtra":""},
"StandardTechnology":{"cardNum":"156","tags":["science"], "cost":"6","resources":{},"prod":{},"type":"blue","cardExtra":"Standard Projects: 3 mc\n(Effect: After you pay for a standard project, except selling patents, you gain 3 mc.)"},
"NitriteReducingBacteria":{"cardNum":"157","tags":["microbe"],"cost":"11","resources":{},"prod":{},"type":"blue","cardExtra":"-> Microbe Resource\nOR 3 Microbe Resource -> TR\n(Action: Add 1 Microbe to this card, or remove 3 Microbes to increase your TR 1 step.\n------\nMicrobe Microbe Microbe (Add 3 Microbes to this card.)"},
"IndustrialMicrobes":{"cardNum":"158","tags":["microbe","building"],"cost":"12","resources":{},"prod":{"energy":1,"steel":1},"type":"green","cardExtra":""},
"Lichen":{"cardNum":"159","tags":["plant"],"cost":"7","resources":{},"prod":{"plant":1},"req":{"temp":-24},"type":"green","cardExtra":""},
"PowerSupplyConsortium":{"cardNum":"160","tags":["power"], "cost":"5","resources":{},"prod":{"energy":1},"req":{"energy":2},"reduce":{"energy":1},"type":"green","cardExtra":""},
"ConvoyFromEuropa":{"cardNum":"161","tags":["space"],"tags":["event"],"cost":"15","resources":{"ocean":1,"card":1},"prod":{},"type":"red","cardExtra":""},
"ImportedGHG":{"cardNum":"162","tags":["earth","space","event"],"cost":"7","resources":{"heat":3},"prod":{"heat":1},"type":"red","cardExtra":""},
"ImportedNitrogen":{"cardNum":"163","tags":["earth","space","event"],"cost":"23","resources":{"tr":1,"plant":4},"prod":{},"type":"red","cardExtra":"Gain Microbe* 3\nGain Animal* 2\n(Add 3 Microbes to ANOTHER card and 2 Animals to ANOTHER card.)"},
"MicroMills":{"cardNum":"164","cost":"3","resources":{},"prod":{"heat":1},"type":"green","cardExtra":""},
"MagneticFieldGenerators":{"cardNum":"165","tags":["building"], "cost":"20","resources":{"tr":3},"prod":{"energy":-4,"plant":2},"type":"green","cardExtra":""},
"Shuttles":{"cardNum":"166","tags":["space"], "cost":"10","resources":{},"prod":{"energy":-1,"mc":2},"req":{"o2":5},"vp":1,"type":"blue","discount":{"space":2},"cardExtra":""},
"ImportOfAdvancedGHG":{"cardNum":"167","tags":["earth","space","event"],"cost":"9","resources":{},"prod":{"heat":2},"type":"red","cardExtra":""},
"Windmills":{"cardNum":"168","tags":["power","building"],"cost":"6","resources":{},"prod":{"energy":1},"req":{"o2":7},"vp":1,"type":"green","cardExtra":""},
"TundraFarming":{"cardNum":"169","tags":["plant"],"cost":"16","resources":{"plant":1},"prod":{"mc":2,"plant":1},"req":{"temp":-6},"vp":2,"type":"green","cardExtra":""},
"AerobrakedAmmoniaAsteroid":{"cardNum":"170","tags":["space"],"tags":["event"],"cost":"26","resources":{},"prod":{"heat":3,"plant":1},"type":"red","cardExtra":"Microbe* Microbe*\n(Add 2 Microbes to ANOTHER card. Increase your heat production 3 steps and your plant productions 1 step.)"},
"MagneticFieldDome":{"cardNum":"171","tags":["building"], "cost":"5","resources":{"tr":1},"prod":{"energy":-2,"plant":1},"type":"green","cardExtra":""},
"Pets":{"cardNum":"172","tags":["earth"],"tags":["animal"],"cost":"10","resources":{},"prod":{},"type":"blue","cardExtra":"any-City: Animal Resource\nANIMALS MAY NOT BE REMOVED FROM THIS CARD.\n(Effect: When any City tile is placed, add an Animal to this card.)\n------\nAnimal Resource\n(Add 1 Animal to this card. 1 VP per 2 Animals here.)\nVP: 1/2 Animal Resource"},
"ProtectedHabitats":{"cardNum":"173","cost":"5","resources":{},"prod":{},"type":"green","cardExtra":"OPPONENTS MAY NOT REMOVE YOUR\nplant Animal Microbe"},
"ProtectedValley":{"cardNum":"174","tags":["plant","building"],"cost":"23","resources":{"greenery":1},"prod":{"mc":2},"type":"green","cardExtra":"(Place on a greenery tile ON AN AREA RESERVED FOR OCEAN, disregarding normal placement restrictions, and increase oxygen 1 step.)"},
"Satellites":{"cardNum":"175","tags":["space"], "cost":"10","resources":{},"prod":{"mc":1},"type":"green","cardExtra":"/Space.\n(Increase your mc production 1 step for each Space tag you have, including this.)"},
"NoctisFarming":{"cardNum":"176","tags":["plant","building"],"cost":"10","resources":{"plant":2},"prod":{"mc":1,},"req":{"temp":-20},"vp":1,"type":"green","cardExtra":""},
"WaterSplittingPlant":{"cardNum":"177","tags":["building"], "cost":"12","resources":{},"prod":{},"req":{"ocean":2},"type":"blue","cardExtra":"energy energy energy -> O2\n(Action: Spend 3 energy to raise oxygen 1 step.)\n------\n(Requires 2 ocean tiles.)"},
"HeatTrappers":{"cardNum":"178","tags":["power","building"],"cost":"6","resources":{},"prod":{"energy":1},"vp":-1,"reduce":{"heat":2},"type":"green","cardExtra":" "},
"SoilFactory":{"cardNum":"179","tags":["building"], "cost":"9","resources":{},"prod":{"energy":-1,"plant":1},"vp":1,"type":"green","cardExtra":""},
"FuelFactory":{"cardNum":"180","tags":["building"], "cost":"6","resources":{},"prod":{"energy":-1,"mc":1,"energy":1,"ti":1},"type":"green","cardExtra":""},
"IceCapMelting":{"cardNum":"181","tags":["event"],"cost":"5","resources":{"ocean":1},"prod":{},"req":{"temp":2},"type":"red","cardExtra":""},
"CorporateStronghold":{"cardNum":"182","tags":["city","building"],"cost":"11","resources":{"city":1},"prod":{"energy":-1,"mc":3,"energy":1},"vp":-2,"type":"green","cardExtra":""},
"BiomassCombustors":{"cardNum":"183","tags":["power","building"],"cost":"4","resources":{},"prod":{"energy":2},"req":{"o2":6},"vp":-1,"reduce":{"plant":1},"type":"green","cardExtra":""},
"Livestock":{"cardNum":"184","tags":["animal"],"cost":"13","resources":{},"prod":{"mc":2,},"req":{"o2":9},"type":"blue","cardExtra":"-> Animal\n(Action: Add 1 Animal to this card.)\n------\nReduce plant 1\n(Requires 9% oxygen. Decrease your plant production 1 step and increase your mc production 2 steps. 1 VP for each Animal on this card.\nVP: 1/Animal"},
"OlympusConference":{"cardNum":"185","tags":["science"],"tags":["earth","building"],"cost":"10","resources":{},"prod":{},"type":"blue","cardExtra":"Science: Science Resource OR -Science Resource +Card\n(When you play a Science tag, including this, either add a Science resource to this card, or remove a Science resource from this card to draw a card.)\n------\nVP: 1\n--- Ed. note: This should likely say .Effect:. on the card."},
"RadSuits":{"cardNum":"186","cost":"6","resources":{},"prod":{"mc":1},"req":{"city":2},"vp":1,"type":"green","cardExtra":""},
"AquiferPumping":{"cardNum":"187","tags":["building"], "cost":"18","resources":{},"prod":{},"type":"blue","cardExtra":"8 mc (steel) -> Ocean Tile\n(Action: Spend 8 mc to place 1 ocean tile. STEEL MAY BE USED as if you were playing a Building card.)"},
"Flooding":{"cardNum":"188","tags":["event"],"cost":"7","resources":{"ocean":1},"prod":{},"vp":-1,"type":"red","cardExtra":"-4 mc*\n(IF THERE ARE TILES ADJACENT TO THIS OCEAN TILE, YOU MAY REMOVE 4 mc FROM THE OWNER OF ONE OF THOSE TILES.)\n"},
"EnergySaving":{"cardNum":"189","tags":["power"], "cost":"15","resources":{},"prod":{},"type":"green","cardExtra":"Increase energy/City*\n(Increase your energy production 1 step for each City tile in play.)"},
"LocalHeatTrapping":{"cardNum":"190","tags":["event"],"cost":"1","resources":{},"prod":{},"type":"red","cardExtra":"-5 heat +4 plant OR +2 Animal* Resource\n(Spend 5 heat to gain either 4 plants, or to add 2 Animals to ANOTHER card.)"},
"PermafrostExtraction":{"cardNum":"191","tags":["event"],"cost":"8","resources":{"ocean":1},"prod":{},"req":{"temp":-8},"type":"red","cardExtra":""},
"InventionContest":{"cardNum":"192","tags":["science"],"tags":["event"],"cost":"2","resources":{},"prod":{},"type":"red","cardExtra":"LOOK AT THE TOP 3 CARDS FROM THE DECK. TAKE 1 OF THEM INTO HAND AND DISCARD THE OTHER 2"},
"Plantation":{"cardNum":"193","tags":["plant"],"cost":"15","resources":{"greenery":1},"prod":{},"req":{"science":2},"type":"green","cardExtra":""},
"PowerInfrastructure":{"cardNum":"194","tags":["power","building"],"cost":"4","resources":{},"prod":{},"type":"blue","cardExtra":"X energy -> X mc\n(Action: Spend any amount of energy and gain that amount of mc.)"},
"IndenturedWorkers":{"cardNum":"195","tags":["event"],"cost":"0","resources":{},"prod":{},"vp":-1,"type":"red","cardExtra":"NEXT CARD: -8 mc\n(The next card you play this generation costs 8 mc less.)\n"},
"LagrangeObservatory":{"cardNum":"196","tags":["science","space"],"cost":"9","resources":{"card":1},"prod":{},"vp":1,"type":"green","cardExtra":""},
"TerraformingGanymede":{"cardNum":"197","tags":["jovian","space"],"cost":"33","resources":{},"prod":{},"vp":2,"type":"green","cardExtra":"TR/Jovian\n(Raise your TR 1 step for each Jovian tag you have, including this.)\n"},
"ImmigrationShuttles":{"cardNum":"198","tags":["earth","space"],"cost":"31","resources":{},"prod":{"mc":5,},"type":"green","cardExtra":"(1 VP for every 3rd City in play.)\nVP: 1/3 City"},
"RestrictedArea":{"cardNum":"199","tags":["science"], "cost":"11","resources":{},"prod":{},"type":"blue","cardExtra":"2 mc -> +Card\n(Action: Spend 2 mc to draw a card.)\n------\nSpecial Tile\n(Place this tile.)"},
"ImmigrantCity":{"cardNum":"200","tags":["city","building"],"cost":"13","resources":{"city":1},"prod":{"energy":-1,"mc":2},"type":"blue","cardExtra":"City*: mc:1\n(Effect: Each time a City tile is placed, including this, increase your mc production 1 step.)\n------\n( and decrease your mc production 2 steps. Place a City tile.)"},
"EnergyTapping":{"cardNum":"201","tags":["power"], "cost":"3","resources":{},"prod":{"energy":1},"vp":-1,"reduce":{"energy":1},"type":"green","cardExtra":""},
"UndergroundDetonations":{"cardNum":"202","tags":["building"], "cost":"6","resources":{},"prod":{},"type":"green","cardExtra":"10 mc -> 2 heat Production"},
"Soletta":{"cardNum":"203","tags":["space"], "cost":"35","resources":{},"prod":{"heat":7},"type":"green","cardExtra":""},
"TechnologyDemonstration":{"cardNum":"204","tags":["science"],"tags":["space"],"tags":["event"],"cost":"5","resources":{"card":2},"prod":{},"type":"red","cardExtra":""},
"RadChemFactory":{"cardNum":"205","tags":["building"], "cost":"8","resources":{"tr":2},"prod":{"energy":-1,},"type":"green","cardExtra":""},
"SpecialDesign":{"cardNum":"206","tags":["science"],"tags":["event"],"cost":"4","resources":{},"prod":{},"type":"red","cardExtra":"Requirement: O2/Ocean/Temperature: +/-2\n(The next card you play this generation is +2 or -2 in global requirements, your choice.)"},
"MedicalLab":{"cardNum":"207","tags":["science","building"],"cost":"13","resources":{},"prod":{},"vp":1,"type":"green","cardExtra":"Increase mc/2 Building\n(Increase your mc production 1 step for every 2 Building tags you have, including this.)\n"},
"AICentral":{"cardNum":"208","tags":["science","building"],"cost":"21","resources":{},"prod":{"energy":-1},"req":{"science":3},"vp":1,"type":"blue","cardExtra":"-> +Card +Card\n(Action: Draw 2 cards.)\n------\n(Requires 3 Science tags to play. .)\n"},
}};
const preludecards = {"corp":{
"CheungShingMARS":{"cardNum":"Z18","tags":["building"], "resources":{"mc":44},"prod":{"mc":3},"type":"blue","discount":{"building":2},"cardExtra":""},
"PointLuna":{"cardNum":"Z19","tags":["earth","space"],"resources":{"mc":38},"prod":{"ti":1},"type":"blue","cardExtra":"Effect:\nEarth: +Card\n(Effect: When you play an Earth tag, including this, draw a card.)"},
"RobinsonIndustries":{"cardNum":"Z20","tags":[],"resources":{"mc":47},"prod":{},"type":"blue","cardExtra":"Action:\n4 mc -> Increase ? 1*\n(Action: Spend 4 mc to increase (one of) your LOWEST PRODUCTION 1 step.)"},
"ValleyTrust":{"cardNum":"Z21","tags":["earth"],"resources":{"mc":37,"prelude":1},"prod":{},"type":"blue","discount":{"science":2},"cardExtra":"As your first action, draw 3 Prelude cards, and play one of them. Discard the other two.)\n"},
"Vitor":{"cardNum":"Z22","tags":["earth"],"resources":{"mc":45,"award":1},"prod":{},"type":"blue","cardExtra":"Effect:\nVP: ?*: 3 mc\n(Effect: When you play a card with a NON-NEGATIVE VP icon, including this, gain 3 mc.)"},
},
"prel":{
"AlliedBanks":{"cardNum":"P01","tags":["earth"],"resources":{"mc":3},"prod":{"mc":4},"type":"green","cardExtra":""},
"AquiferTurbines":{"cardNum":"P02","tags":["power"], "resources":{"mc":-3,"ocean":1},"prod":{"energy":2},"type":"green","cardExtra":""},
"Biofuels":{"cardNum":"P03","tags":["microbe"],"resources":{"plant":2},"prod":{"plant":1,"energy":1},"type":"green","cardExtra":""},
"Biolab":{"cardNum":"P04","tags":["science"], "resources":{"plant":1,"card":3},"prod":{},"type":"green","cardExtra":""},
"BiosphereSupport":{"cardNum":"P05","tags":["plant"],"resources":{},"prod":{"mc":-1,"plant":2},"type":"green","cardExtra":""},
"BusinessEmpire":{"cardNum":"P06","tags":["earth"],"resources":{"mc":-6},"prod":{"mc":6},"type":"green","cardExtra":""},
"DomeFarming":{"cardNum":"P07","tags":["plant","building"],"resources":{},"prod":{"mc":2,"plant":1},"type":"green","cardExtra":""},
"Donation":{"cardNum":"P08","resources":{"mc":21},"prod":{},"type":"green","cardExtra":""},
"EarlySettlement":{"cardNum":"P09","tags":["city","building"],"resources":{"city":1},"prod":{"plant":1},"type":"green","cardExtra":""},
"EcologyExperts":{"cardNum":"P10","tags":["plant","microbe"],"resources":{},"prod":{"plant":1},"type":"green","cardExtra":"PLAY A CARD FROM HAND, IGNORING GLOBAL REQUIREMENTS\n(Increase your plant production 1 step.)"},
"EccentricSponsor":{"cardNum":"P11","resources":{},"prod":{},"type":"green","cardExtra":"PLAY A CARD FROM HAND, REDUCING ITS COST BY 25 mc"},
"ExperimentalForest":{"cardNum":"P12","tags":["plant"],"resources":{"greenery":1,"draw":{"plant":2}},"prod":{},"type":"green","cardExtra":""},
"GalileanMining":{"cardNum":"P13","tags":["jovian"],"resources":{"mc":-5},"prod":{"ti":2},"type":"green","cardExtra":""},
"GreatAquifer":{"cardNum":"P14","resources":{"ocean":2},"prod":{},"type":"green","cardExtra":""},
"HugeAsteroid":{"cardNum":"P15","resources":{"temp":3, "mc":-5},"prod":{},"type":"green","cardExtra":""},
"IoResearchOutpost":{"cardNum":"P16","tags":["science","jovian"],"resources":{"card":1},"prod":{"ti":1},"type":"green","cardExtra":""},
"Loan":{"cardNum":"P17","resources":{"mc":30},"prod":{"mc":-2},"type":"green","cardExtra":""},
"MartianIndustries":{"cardNum":"P18","tags":["building"], "resources":{"mc":6},"prod":{"energy":1,"steel":1},"type":"green","cardExtra":""},
"MetalRichAsteroid":{"cardNum":"P19","resources":{"temp":1,"steel":4,"ti":4},"prod":{},"type":"green","cardExtra":""},
"MetalsCompany":{"cardNum":"P20","resources":{},"prod":{"mc":1,"steel":1,"ti":1},"type":"green","cardExtra":""},
"MiningOperations":{"cardNum":"P21","tags":["building"], "resources":{"steel":4},"prod":{"steel":2},"type":"green","cardExtra":""},
"Mohole":{"cardNum":"P22","tags":["building"], "resources":{"heat":3},"prod":{"heat":3},"type":"green","cardExtra":""},
"MoholeExcavation":{"cardNum":"P23","tags":["building"], "resources":{"heat":2},"prod":{"heat":2,"steel":1},"type":"green","cardExtra":""},
"NitrogenDelivery":{"cardNum":"P24","resources":{"tr":1,"mc":5},"prod":{"plant":1},"type":"green","cardExtra":""},
"OrbitalConstructionYard":{"cardNum":"P25","tags":["space"], "resources":{"ti":4},"prod":{"ti":1},"type":"green","cardExtra":""},
"PolarIndustries":{"cardNum":"P26","tags":["building"], "resources":{"ocean":1},"prod":{"heat":2},"type":"green","cardExtra":""},
"PowerGeneration":{"cardNum":"P27","tags":["power"], "resources":{},"prod":{"energy":3},"type":"green","cardExtra":""},
"ResearchNetwork":{"cardNum":"P28","tags":["wild"],"resources":{"card":3},"prod":{"mc":1},"type":"green","cardExtra":""},
"SelfSufficientSettlement":{"cardNum":"P29","tags":["city","building"],"resources":{"city":1},"prod":{"mc":2},"type":"green","cardExtra":""},
"SmeltingPlant":{"cardNum":"P30","tags":["building"], "resources":{"o2":2,"steel":5},"prod":{},"type":"green","cardExtra":""},
"SocietySupport":{"cardNum":"P31","resources":{},"prod":{"mc":-1,"plant":1,"energy":1,"heat":1},"type":"green","cardExtra":""},
"Supplier":{"cardNum":"P32","tags":["power"], "resources":{"steel":4},"prod":{"energy":2},"type":"green","cardExtra":""},
"SupplyDrop":{"cardNum":"P33","resources":{"ti":3,"steel":8,"plant":3},"prod":{},"type":"green","cardExtra":""},
"UNMIContractor":{"cardNum":"P34","tags":["earth"],"resources":{"tr":3,"card":1},"prod":{},"type":"green","cardExtra":""},
"AcquiredSpaceAgency":{"cardNum":"P35","resources":{"ti":6,"draw":{"space":2}},"prod":{},"type":"green","cardExtra":""}
},
"proj":{
"HousePrinting":{"cardNum":"P36","tags":["building"], "cost":"10","resources":{},"prod":{"steel":1},"vp":1,"type":"green","cardExtra":""},
"LavaTubeSettlement":{"cardNum":"P37","tags":["city","building"],"cost":"15","resources":{"city":1},"prod":{"energy":-1,"mc":2,},"type":"green","cardExtra":"(Place a City tile ON A VOLCANIC AREA, same as Lava Flows, regardless of adjacent cities.)"},
"MartianSurvey":{"cardNum":"P38","tags":["science"],"tags":["event"],"cost":"9","resources":{"card":2},"prod":{},"req":{"maxo2":4},"vp":1,"type":"red","cardExtra":""},
"Psychrophiles":{"cardNum":"P39","tags":["microbe"],"cost":"2","resources":{},"prod":{},"req":{"maxtemp":-20},"type":"blue","cardExtra":"-> Microbe\nplant cards: Microbe = 2mc\n(Action: Add a microbe to this card.\nEffect: When paying for a plant card, microbes here may be used as 2 mc each.)\n------\n(Requires temperature -20 C or colder.)"},
"ResearchCoordination":{"cardNum":"P40","tags":["wild"],"cost":"4","resources":{},"prod":{},"type":"green","cardExtra":""},
"SFMemorial":{"cardNum":"P41","tags":["building"], "cost":"7","resources":{"card":1},"prod":{},"vp":1,"type":"green","cardExtra":""},
"SpaceHotels":{"cardNum":"P42","tags":["earth","space"],"cost":"12","resources":{},"prod":{"mc":4},"req":{"earth":2},"type":"green","cardExtra":""},
}};
